In [11]:
import torch

# 假设有一个形状为 (b, dim) 的张量
b = 2
dim = 6
tensor = torch.randn(b, dim)

# 将张量分成形状为 (b, n, dim/n) 的张量
n = 3
tensor_split = tensor.view(b, n, dim // n)

print("Original tensor shape:", tensor.shape)
print("Split tensor shape:", tensor_split.shape)


Original tensor shape: torch.Size([2, 6])
Split tensor shape: torch.Size([2, 3, 2])


In [3]:
import torch

# 创建一个形状为 (3, 4) 的张量
tensor = torch.randn(3, 4)

# 创建一个形状为 (4,) 的向量
vector = torch.randn(4)
print(vector)
# 在首部拼接向量到张量
concatenated_tensor = torch.cat([vector.unsqueeze(0), tensor], dim=0)

print(concatenated_tensor)
print("Concatenated tensor shape:", concatenated_tensor.shape)


tensor([ 1.2364, -0.2488,  1.4169,  0.0185])
tensor([[ 1.2364, -0.2488,  1.4169,  0.0185],
        [-0.7423, -0.6305, -0.0449, -0.3888],
        [-0.6575,  1.3456, -0.7135, -0.6883],
        [-1.0485, -0.3414,  0.0951, -0.0729]])
Concatenated tensor shape: torch.Size([4, 4])


In [1]:
import torch

# 创建示例数据
tensor = torch.randn(1024, 5, 32)

# 取每组第一个元素
first_elements = tensor[:, 0, :]

print("First elements tensor shape:", first_elements.shape)


First elements tensor shape: torch.Size([1024, 32])


In [9]:
import torch

# 创建示例数据
tensor = torch.randn(25000, 128)

# 计算两两之间的距离
distances = torch.cdist(tensor, tensor)

# 将对角线上的值设置为一个很大的数，以排除自己与自己的情况
for i in range(len(distances)):
    distances[i, i] = float('inf')

print("Distances tensor shape:", distances.shape)


Distances tensor shape: torch.Size([25000, 25000])


In [3]:
import struct
def read_graph(filename):
    graph_data = []
    with open(filename, 'rb') as file:
        while True:
            # 读取节点的邻居数量
            gk_data = file.read(4)
            if not gk_data:
                break  # 文件读取完毕
            gk = struct.unpack('I', gk_data)[0]  # 解析为无符号整数

            # 读取邻居列表
            neighbors_data = file.read(4 * gk)
            neighbors = struct.unpack(f'{gk}I', neighbors_data)  # 解析为无符号整数列表

            # 添加节点数据到结果列表
            graph_data.append(neighbors)

    return graph_data

# 读取文件
filename = "/home/sfy/study/data/sift_small/saft_learn_200nn_efanna.graph"  # 将路径替换为你保存的文件路径
graph_data = read_graph(filename)

# 打印读取的数据
for i, neighbors in enumerate(graph_data):
    print(f"Node {i + 1}: Neighbors={neighbors}")
print(len(graph_data))


In [1]:
import torch

def pairwise_weighted_fusion(tensor):
    """
    对输入张量中的每对向量进行加权融合。

    参数：
    - tensor: 输入张量，形状为 (N, D)，其中 N 是向量数量，D 是向量维度。

    返回值：
    - fused_tensor: 融合后的张量，形状与输入张量相同。
    """
    N, D = tensor.shape

    # 创建一个新的张量来存储融合结果
    fused_tensor = torch.zeros(N, D)

    # 遍历每对向量
    for i in range(N):
        for j in range(N):
            if i != j:  # 排除自己和自己融合
                # 计算加权平均值
                weight_i = torch.randn(1)  # 假设权重为随机值
                weight_j = torch.randn(1)  # 假设权重为随机值
                fused_tensor[i] += tensor[i] * weight_i + tensor[j] * weight_j

    return fused_tensor

# 示例数据
tensor = torch.randn(1024, 32)

# 调用函数进行加权融合
fused_tensor = pairwise_weighted_fusion(tensor)
print("Fused tensor shape:", fused_tensor.shape)


Fused tensor shape: torch.Size([1024, 32])


In [2]:
import torch

# 创建示例数据
tensor = torch.randn(1024, 32)

# 计算加权融合
combined_tensor = torch.zeros(1024, 1024, 32)
for i in range(1024):
    for j in range(1024):
        if i != j:  # 排除自己和自己融合
            # 计算加权平均值
            weight_i = torch.randn(1)  # 假设权重为随机值
            weight_j = torch.randn(1)  # 假设权重为随机值
            combined_tensor[i, j] = tensor[i] * weight_i + tensor[j] * weight_j

print("Combined tensor shape:", combined_tensor.shape)


Combined tensor shape: torch.Size([1024, 1023, 32])


In [10]:
import numpy as np

# 示例数组
arr = np.array([
    [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
    [[10, 11, 12], [13, 14, 15], [16, 17, 18]],
    [[19, 20, 21], [22, 23, 24], [25, 26, 27]]
])

# 示例下标元组
neighbor = [0,2]

# 使用元组下标从数组中取出元素
# selected_elements = [arr[idx] for idx in indices]
select = [arr[0,idx] for idx in neighbor]

print("Selected elements:", select)


Selected elements: [array([1, 2, 3]), array([7, 8, 9])]


In [13]:
print(graph_data[0])


(2, 6, 4585, 9256, 140, 9415, 114, 4399, 8002, 8797, 5976, 3033, 3912, 9040, 6335, 5131, 4589, 6517, 118, 4390, 4709, 9102, 205, 6489, 4729, 233, 4629, 9769, 5430, 4, 4391, 7839, 8441, 7007, 1525, 3911, 724, 6107, 6922, 474, 1647, 4828, 9170, 1656, 2995, 7117, 73, 3150, 4560, 4331, 8215, 9095, 4663, 104, 1275, 4592, 7050, 2120, 74, 2421, 3053, 5539, 1270, 8230, 1153, 4742, 5025, 4776, 5525, 8176, 4640, 4646, 3325, 5056, 1170, 5861, 9791, 4726, 4483, 5651, 4680, 7399, 1449, 4853, 8, 4553, 603, 4042, 962, 1546, 8649, 8761, 6683, 8599, 8915, 1659, 18, 9356, 3377, 4504, 4738, 3469, 5169, 2941, 9473, 3433, 4700, 5002, 4172, 5296, 1288, 4537, 4708, 2547, 6531, 5938, 7422, 4660, 1959, 1399, 6423, 78, 6839, 9105, 7309, 7049, 3600, 4737, 5220, 5367, 5297, 6266, 2462, 8661, 4393, 4593, 1144, 8263, 4639, 7662, 10, 2661, 704, 5354, 5091, 4509, 608, 9355, 688, 3382, 4725, 1911, 4854, 20, 57, 29, 4659, 784, 8300, 2655, 6446, 7264, 306, 5303, 252, 1639, 543, 1331, 4484, 9397, 8214, 4705, 4826, 5320, 

In [43]:
import torch

# 示例邻居张量
neighbor = torch.tensor([2, 1, 0])

# 示例距离张量
dist = torch.tensor([
    [[1.5, 2.5, 13.5], [4.5, 5.5, 6.5], [7.5, 8.5, 14.5]],
    [[10.5, 11.5, 12.5], [13.5, 14.5, 15.5], [16.5, 17.5, 18.5]],
    [[19.5, 20.5, 21.5], [22.5, 23.5, 24.5], [25.5, 26.5, 27.5]]
])

# 根据距离数组中的距离对邻居进行排序
sorted_indices = torch.argsort(dist[0, neighbor,2])
sorted_neighbors = neighbor[sorted_indices]

print("Sorted neighbors:", sorted_neighbors)


Sorted neighbors: tensor([1, 0, 2])


In [1]:
import torch

# 示例数组
arr = torch.tensor([10, 20, 30, 40, 50])

# 一组索引
indices = torch.tensor([0, 2, 4])

# 使用 torch.index_select() 函数从数组中取出对应元素
selected_elements = torch.index_select(arr, 0, indices)

print(selected_elements)


tensor([10, 30, 50])


In [2]:
# 定义数组
array = ['a', 'b', 'c', 'd', 'e']

# 定义索引数组
indexes = [0, 2, 4]

# 使用列表推导式获取对应元素
result = [array[i] for i in indexes]

# 输出结果
print(result)  # 输出: ['a', 'c', 'e']


['a', 'c', 'e']
